In recent nightlies we are hitting errors like the following:
     error: an associated constant with this name may be added to the standard library in the future
       --> libm/src/math/support/float_traits.rs:248:48
        |
    248 |               const SIGN_MASK: Self::Int = 1 << (Self::BITS - 1);
        |                                                  ^^^^^^^^^^
    ...
    324 | / float_impl!(
    325 | |     f32,
    326 | |     u32,
    327 | |     i32,
    ...   |
    333 | |     fmaf32
    334 | | );
        | |_- in this macro invocation
        |
        = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
        = note: for more information, see issue #2
        = note: `-D unstable-name-collisions` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(unstable_name_collisions)]`
        = note: this error originates in the macro `float_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
    help: use the fully qualified path to the associated const
        |
    248 -             const SIGN_MASK: Self::Int = 1 << (Self::BITS - 1);
    248 +             const SIGN_MASK: Self::Int = 1 << (<f32 as float_traits::Float>::BITS - 1);
        |
    help: add `#![feature(float_bits_const)]` to the crate attributes to enable `core::f32::<impl f32>::BITS`
       --> libm/src/lib.rs:26:1
        |
     26 + #![feature(float_bits_const)]
        |

Using fully qualified syntax is verbose and `BITS` only exists since
recently, so allow this lint instead.